<?php
/**
 * 游戏模块的配置信息
 * @author yunyi
 */
namespace enum;

use ZPHP\Exception\GameException;
use ZPHP\Exception\Error;
class EnumGameObject
{
    const EVENT = 'Event';
    const FLEET = 'Fleet';
    const ROLE_BUILDING = 'RoleBuilding';
    const PLANET_BUILDING = 'PlanetBuilding';
    const COLONY_PLANET = 'ColonyPlanet';
    const HOME_PLANET = 'HomePlanet';
    const MATERIAL = 'Material';
    const QEVENT = 'QEvent';
    const ROLE = 'Role';
    const ROLE_SHIP = 'RoleShip';
    const USER = 'User';
    const SCAN = 'Scan';
    const PATH = 'Path';
    const ROLE_TASK = 'RoleTask';
    const ROLE_TASK_LOG = 'RoleTaskLog';
    const ROLE_TASK_GOAL = 'RoleTaskGoal';
    const ROLE_TECH = 'RoleTech';
    const BATTLE = 'Battle';
    const ROLE_ITEM = 'RoleItem';
    const CLIENT_THRIFT = 'ClientThrift';
    const MAIL = 'Mail';
    const ROLE_SATELLITE = 'RoleSatellite';
    const SATELLITE_FORM = 'SatelliteForm';
    const LEAGUE = 'League';
    const FRIEND = 'Friend';
    const ROLE_COMMODITY = 'RoleCommodity';
    const VIP = 'Vip';
    const ONLINE = 'Online';
    const RECHARGE = 'Recharge';
    const ROLE_SCREENING = 'RoleScreening';
    const ROLE_ELITE = 'RoleElite';
    const ROLE_COUNTER = 'RoleCounter';
    const KEYWORD = 'KeyWord';
    const ROLE_ONLINE_AWARD = 'RoleOnlineAward';
    const ROLE_CAPTAIN = 'RoleCaptain';
    const ROLE_SOLAR_EXPLORE = 'RoleSolarExplore';
    const ROLE_DROP = 'RoleDrop';
    const ROLE_SKILL = 'RoleSkill';
    const ACTION_LOG = 'ActionLog';
    const ROLE_LIVENESS = 'RoleLiveness';
    const IC_LOG = 'IcLog';
    const MATERIAL_LOG = 'MaterialLog';
    const ACTIVITY_LOG = 'ActivityLog';
    const GUIDE_RECORD = 'GuideRecord';
    const UI_OPEN = 'UiOpen';
    const BATTLE_LOG = 'BattleLog';
    const ROLE_REGULAR_CD = 'RoleRegularCd';
    const CBT_ONE = 'CbtOne';
    const ROLE_SHIP_RESEARCH = 'RoleShipResearch';
    const RANKING_LIST = 'RankingList';
    const LOOTING_LOG = 'LootingLog';
    const ROLE_EXCHANGE = 'RoleExchange';
    const SYSTEM_RECORD = 'SystemRecord';
    const DY_Effect = 'DyEffect';
    const VIRTUAL_LOOTING = 'VirtualLooting';
    const ROLE_DEBRIS = 'RoleDebris';
    const ROLE_DISCOUNT = 'RoleDiscount';
    const ROLE_SIGN = 'RoleSign';
    const ITEM_LOG = 'ItemLog';
    const RANKING_LOG = 'RankingLog';
    const RAND_EXCHANGE	= 'RandExchange';
    const BATTLE_FIELD = 'BattleField';
    const BATTLE_QUEUE = 'BattleQueue';
    const BOSS_DKP = 'BossDkp';
    const DY_BOSS = 'DyBoss';
    const BASE = 'Base';
    const BASE_BUILDING = 'BaseBuilding';
    const BASE_SAT_FORM = 'BaseSatForm';
    const BASE_SAT = 'BaseSat';
    const ROLE_CREDIT_LOG = 'RoleCreditLog';
    const ROLE_CHIP = 'RoleChip';
    const ROLE_TRIALS = 'RoleTrials';
    const ROLE_DEGREE = 'RoleDegree';
    const CHIP_LOG = 'ChipLog';
    const STRONGHOLD = 'Stronghold';
    const ASTARGATE = 'AStargate';
    const SHIP_LOG = 'ShipLog';
    const BASE_LOG = 'BaseLog';
    const STRONGHOLD_ACTIVITY = 'StrongholdActivity';
    const STRONGHOLD_ROLEDKP = 'StrongholdRoleDkp';
    const HATTER = 'Hatter';
    const MAILBACK = 'MailBack';
    const ROLEMAILLOG = 'RoleMailLog';
    const ARENA_REWARD_LOG = 'ArenaRewardLog';
    const CHALLENGE_REWARD_LOG = 'ChallengeRewardLog';
    const ROLE_SCENES = 'RoleScenes';
    const ROLE_TEAM = 'RoleTeam';
    const ROLE_BINDTEAM = 'RoleBindTeam';
    const ROLE_COIN = 'RoleCoin';
    const BUSINESS = 'Business';
    const FLEET_MIRROR = 'FleetMirror';
    const PLANET_DEFEND = 'PlanetDefend';
    const PLANET_DEFEND_POS = 'PlanetDefendPos';
    const ROLE_FORTUNATE = 'RoleFortunate';
    const FORTUNATE_ACTIVITY = 'FortunateActivity';
    const ACTIVITY_EXCHANGE = 'ActivityExchange';
    const FORTUNATE_LOG = 'FortunateLog';
    const ROLE_USER_AWARD = 'RoleUserAward';
    const DEFEND_LOG = 'DefendLog';
    const SLOTMACHINE = 'SlotMachine';
    const ROLE_SLOTMACHINE = 'RoleSlotMachine';
    const SLOTMACHINE_LOG = 'SlotMachineLog';
    const SKYLEVEL_LOG = 'SkyLevelLog';
    const ACTIVITY_BOX = 'ActivityBox';
    const ROLE_ACTIVITY_BOX = 'RoleActivityBox';
    const ACTIVITYBOX_LOG = 'ActivityBoxLog';
    const MATERIALDETAIL_LOG = 'MaterialDetailLog';
    const ROLE_SH_WEEK = 'RoleSHWeek';
    const CARD_RP_LOG = 'CardRpLog';
    const SH_AWARD_LOG = 'ShAwardLog';
    const ROLE_FORMATION = 'RoleFormation';
    const DY_SOLAR = 'DySolar';
    const ROLE_BUILD_ITEM = 'RoleBuildItem';
    const ROLE_GEAR = 'RoleGear';
    const ARENA_ROLE = 'ArenaRole';
    const ARENA_RANKING = 'ArenaRanking';
    const ARENA_RECORD = 'ArenaRecord';
    const ROLE_EXERCISE = 'RoleExercise';
    const ROLE_EXPEDITION_ZONE = 'RoleExpeditionZone';
    const ROLE_RUINS = 'RoleRuins';
    const ROLE_RUINS_LOG = 'RoleRuinsLog';
    const STRONGHOLD_BUFF = 'StrongholdBuff';
    const STRONGHOLD_BATTLE_LOG = 'StrongholdBattleLog';
    const RECHARGE_LOG_TX = 'RechargeLogTx';
    const ROLE_REMAKE = 'RoleStarShipRemake';
    const ROLE_DETECTION = 'RoleDetection';
    const ROLE_DETECTION_TASK = 'RoleDetectionTask';
    const ROLE_LOTERY = 'RoleLotery';
    const ROLE_SERVER_GOAL = 'RoleServerGoal';
    const RAIDERARK_DY = 'RaiderArkDy';
    const RAIDERARK_AREA = 'RaiderArkArea';
    const RAIDERARK_CREDITS = 'RaiderArkCredits';
    const RAIDERARK_REPORT = 'RaiderArkReport';
    const ROLE_HONOR_MEDAL = 'RoleHonorMedal';
    const ROLE_HONOR_MEDAL_PRO = 'RoleHonorMedalPro';
    const ROLE_HFRONT_LINE = 'RoleHFrontLine';
    const BROAD_CAST = 'BroadCast';
    const REFINE_REPORT = 'RefineReport';
    const DEATH_BATTLE = 'DeathBattle';
    const DEATH_BATTLE_REPORT = 'DeathBattleReport';
    const ROLE_SOLAR_SCREENING = 'RoleSolarScreening';
    const FIGHTER = 'Fighter';
    const FIGHTER_LOG = 'FighterLog';

    // cross
    const ARENA_SHIP = 'ArenaShip';
    const CHALLENGE_ROLE = 'ChallengeRole';
    const CHALLENGE_FLEET = 'ChallengeFleet';
    const CHALLENGE = 'Challenge';
    const CROLE_COUNTER = 'CRoleCounter';
    const CONVENE = 'Convene';
    const CONVENE_LOG = 'ConveneLog';
    const CROSS_ROLE = 'CrossRole';
    const CROSS_FLEET = 'CrossFleet';
    const STRONGHOLD_SCORE = 'StrongholdScore';
    const STRONGHOLD_NOTICE = 'StrongholdNotice';
    const CROSS_ITEM = 'CrossItem';
    const STRONGHOLD_AWARD_LOG = 'StrongholdAwardLog';
    const VIRTUAL_FLEET = 'VirtualFleet';
    const VIRTUAL_ROLE_FLEET = 'VirtualRoleFleet';

    // sys
    const ACTION = 'Action';
    const AVATAR = 'Avatar';
    const BANNED_WORD = 'BannedWord';
    const BUILDING = 'Building';
    const COMMODITY = 'Commodity';
    const EVENT_SET = 'EventSet';
    const FACTION = 'Faction';
    const GALAXY = 'Galaxy';
    const GALAXY_PATH = 'GalaxyPath';
    const GAME_SETTING = 'GameSetting';
    const ITEM = 'Item';
    const PLANET = 'Planet';
    const ROLE_LEVEL = 'RoleLevel';
    const SERVER = 'Server';
    const SOLAR = 'Solar';
    const STAR_SHIP = 'StarShip';
    const TASK = 'Task';
    const TASK_GOAL = 'TaskGoal';
    const TASK_SERIAL = 'TaskSerial';
    const TECH = 'Tech';
    const TECH_EFFECT_TYPE = 'TechEffectType';
    const MOB = 'Mob';
    const MOB_FLEET = 'MobFleet';
    const LAIR = 'Lair';
    const SKILL = 'Skill';
    const SATELLITE = 'Satellite';
    const POWER_ACT = 'PowerAct';
    const LEAGUE_POWER = 'LeaguePower';
    const VIP_EXP = 'VipExp';
    const VIP_FUNC = 'VipFunc';
    const VIP_POWER = 'VipPower';
    const VIP_AWARD = 'VipAward';
    const BUFF_EFFECT = 'BuffEffect';
    const GALAXY_CHAPTER = 'GalaxyChapter';
    const SOLAR_SCREENING = 'SolarScreening';
    const ELITE_SCREENING = 'EliteScreening';
    const COUNTER = 'Counter';
    const ONLINE_AWARD = 'OnlineAward';
    const CAPTAIN = 'Captain';
    const CAPTAIN_LEVEL = 'CaptainLevel';
    const CAPTAIN_GRADE = 'CaptainGrade';
    const CAPTAIN_PROPERTY = 'CaptainProperty';
    const CAPTAIN_ABILITY = 'CaptainAbility';
    const AWARD_DROP = 'AwardDrop';
    const MAIL_TEMPLATE = 'MailTemplate';
    const LIVENESS = 'Liveness';
    const LIVENESS_AWARDS = 'LivenessAwards';
    const SIGN_AWARDS = 'SignAwards';
    const ACTIVITY = 'Activity';
    const SYNTHESIZE = 'Synthesize';
    const REGULAR_CD = 'RegularCd';
    const GUIDE = 'Guide';
    const SHIP_RESEARCH = 'ShipResearch';
    const MILITARY_RANK = 'MilitaryRank';
    const CHAT_TEMPLATE = 'ChatTemplate';
    const EXCHANGE = 'Exchange';
    const BUILDING_LEVEL = 'BuildingLevel';
    const EFFECT = 'Effect';
    const EFFECT_TYPE = 'EffectType';
    const VIRTUAL_ROLE = 'VirtualRole';
    const LANGUAGE = 'Language';
    const SCREENING_STAR = 'ScreeningStar';
    const ACTIVITY_AWARD = 'ActivityAward';
    const ADDUP_AWARDS = 'AddUpAwards';
    const RAND_GOODS = 'RandGoods';
    const BATTLE_SET = 'BattleSet';
    const BOSS = 'Boss';
    const BOSS_RANKING = 'BossRanking';
    const BOSS_LEVEL = 'BossLevel';
    const ACTIVITY_ACTION = 'ActivityAction';
    const CHIP = 'Chip';
    const CHIP_LEVEL = 'ChipLevel';
    const TRIALS_CHAPTER = 'TrialsChapter';
    const TRIALS_SCREENING = 'TrialsScreening';
    const DEGREE = 'Degree';
    const GAME_MODULE = 'GameModule';
    const PLANET_PATH = 'PlanetPath';
    const SHACTIVITY = 'SHActivity';
    const SHDKPAWARD = 'SHDkpAward';
    const STRONGHOLD_PLANET = 'StrongholdPlanet';
    const TRIALS_RANK_AWARD = 'TrialsRankAward';
    const STRONGHOLD_LAIR = 'StrongholdLair';
    const CROSS = 'Cross';
    const CROSS_SERVER = 'CrossServer';
    const ARENA_LAIR = 'ArenaLair';
    const ARENA_AWARD = 'ArenaAward';
    const CHALLENGE_AWARD = 'ChallengeAward';
    const SCENES = 'Scenes';
    const LEAGUE_LEVEL = 'LeagueLevel';
    const ACTIVITY_PROGRESSIVE = 'ActivityProgressive';
    const FORTUNATE_AWARD = 'FortunateAward';
    const FORTUNATE_RANK_AWARD = 'FortunateRankAward';
    const EXCHANGE_CLASS = 'ExchangeClass';
    const USER_AWARD = 'UserAward';
    const USER_AWARD_USER = 'UserAwardUser';
    const FORTUNATE_AWARD_GROUP = 'FortunateAwardGroup';
    const AWARD_TIME_DROP = 'AwardTimeDrop';
    const EQUIP_EFFECT = 'EquipEffect';
    const ACTIVITY_GUI = 'ActivityGui';
    const WHITE_LIST = 'WhiteList';
    const MISC = 'Misc';
    const STATIC_SLOTMACHINE = 'StaticSlotMachine';
    const SLOTMACHINE_TYPE = 'SlotMachineType';
    const SLOTMACHINE_GROUP = 'SlotMachineGroup';
    const SKYLEVEL_AWARD = 'SkyLevelAward';
    const SLOTMACHINE_RANK_AWARD = 'SlotMachineRankAward';
    const STATIC_ACTIVITY_BOX = 'StaticActivityBox';
    const BOX_STEP = 'BoxStep';
    const BOX = 'Box';
    const BOX_RANK_AWARD = 'BoxRankAward';
    const STRONGHOLD_AWARD = 'StrongholdAward';
    const STRONGHOLD_DKP_SCORE = 'StrongholdDkpScore';
    const WEEK_TITLE = 'WeekTitle';
    const CROSS_MODULE = 'CrossModule';
    const FORMATIONLINKAGE = 'FormationLinkage';
    const PLATFORM_CHARGE = 'PlatformCharge';
    const SHIP_LEVEL = 'ShipLevel';
    const SHIP_STAR = 'ShipStar';
    const BUILD_ITEM = 'BuildingItem';
    const GEAR = 'Gear';
    const GEAR_LEVEL = 'GearLevel';
    const GEAR_GRADE ='GearGrade';
    const EXPLORE_AWARD ='ExploreAward';
    const SOLAR_AREA ='SolarArea';
    const LOOTING_AWARD ='LootingAward';
    const VIRTUAL_FLEET_SET = 'VirtualFleetSet';
    const RAND_NAME = 'RandName';
    const EXERCISE_CHAPTER = 'ExerciseChapter';
    const EXERCISE_SCREENING = 'ExerciseScreening';
    const EXPEDITION_ZONE = 'ExpeditionZone';
    const RUINS_CLASS = 'RuinsClass';
    const RUINS_COST = 'RuinsCost';
    const FUNC_OPEN = 'FuncOpen';
    const DEFENSE_NPC = 'DefenseNpc';
    const TECH_LEVEL = 'TechLevel';
    const GOLD_BOX = 'GoldBox';
    const CHECK_TABLE = 'CheckTable';
    const STARSHIP_REMAKE = 'StarShipRemake';
    const STARSHIP_REMAKE_LEVEL = 'StarShipRemakeLevel';
    const STARSHIP_ABILITY = 'StarShipAbility';
    const DETECTION_TASK = 'DetectionTask';
    const LOTERY_CLASS = 'LoteryClass';
    const LOTERY = 'Lotery';
    const SERVER_GOAL = 'ServerGoal';
    const RAIDERARK_ACTIVITY = 'RaiderArkActivity';
    const RAIDERARK_LEVEL = 'RaiderArkLevel';
    const STARSHIP_PROPERTY = 'StarshipProperty';
    const HONOR_MEDAL = 'HonorMedal';
    const HONOR_MEDAL_PRO = 'HonorMedalPro';
    const HONOR_MEDAL_SUIT = 'HonorMedalSuit';
    const HFRONT_LINE_ACTIVITY = 'HFrontLineActivity';
    const HFRONT_LINE_AWARD = 'HFrontLineAward';
    const EXCHANGE_GROUP = 'ExchangeGroup';
    const DATA_VER = 'DataVer';
    const SCHEDULER_TIMER = 'SchedulerTimer';
    const DEATH_BATTLE_ACTIVITY = 'DeathBattleActivity';
    const DEATH_BATTLE_MULTI_KILL = 'DeathBattleMultiKill';
    const DEATH_BATTLE_ACTIVE_CHEST = 'DeathBattleActiveChest';
    const DEATH_BATTLE_END_AWARD = 'DeathBattleEndAward';
    const LAN_DB = 'LanDb';
    const FIGHTER_CAREER = 'FighterCareer';
    const FIGHTER_SUIT = 'FighterSuit';
    const FIGHTER_GRADE = 'FighterGrade';
    const FIGHTER_LEVEL = 'FighterLevel';
    const CUSTOM_FUNCTION = 'CustomFunction';

    // DYNAMIC
    public static $Event = array('Name'=>'Event','Route'=>'api\module\event\Event','ConstRoute'=>'api\module\event\Constant','Type'=>'DYNAMIC');
    public static $Fleet = array('Name'=>'Fleet','Route'=>'api\module\fleet\Fleet','ConstRoute'=>'api\module\fleet\Constant','Type'=>'DYNAMIC');
    public static $RoleBuilding = array('Name'=>'RoleBuilding','Route'=>'api\module\gamebuilding\RoleBuilding','ConstRoute'=>'api\module\gamebuilding\rolebuilding\Constant','Type'=>'DYNAMIC');
    public static $PlanetBuilding = array('Name'=>'PlanetBuilding', 'Route'=>'api\module\gamebuilding\PlanetBuilding','ConstRoute'=>'api\module\gamebuilding\planetbuilding\Constant','Type'=>'DYNAMIC');
    public static $ColonyPlanet = array('Name'=>'ColonyPlanet', 'Route'=>'api\module\gameplanet\ColonyPlanet','ConstRoute'=>'api\module\gameplanet\colonyplanet\Constant','Type'=>'DYNAMIC');
    public static $HomePlanet = array('Name'=>'HomePlanet', 'Route'=>'api\module\gameplanet\HomePlanet','ConstRoute'=>'api\module\gameplanet\homeplanet\Constant','Type'=>'DYNAMIC');
    public static $Material = array('Name'=>'Material', 'Route'=>'api\module\material\Material','ConstRoute'=>'api\module\material\Constant','Type'=>'DYNAMIC');
    public static $QEvent = array('Name'=>'QEvent','Route'=>'api\module\qevent\QEvent','ConstRoute'=>'api\module\qevent\Constant','Type'=>'DYNAMIC');
    public static $Role = array('Name'=>'Role','Route'=>'api\module\role\Role','ConstRoute'=>'api\module\role\Constant','Type'=>'DYNAMIC');
    public static $RoleShip = array('Name'=>'RoleShip','Route'=>'api\module\roleship\RoleShip','ConstRoute'=>'api\module\roleship\Constant','Type'=>'DYNAMIC');
    public static $User = array('Name'=>'User','Route'=>'api\module\user\User','ConstRoute'=>'api\module\user\Constant','Type'=>'DYNAMIC');
    public static $Scan = array('Name'=>'Scan','Route'=>'api\module\scan\Scan','ConstRoute'=>'api\module\scan\Constant','Type'=>'DYNAMIC');
    public static $Path = array('Name'=>'Path','Route'=>'api\module\path\Path','ConstRoute'=>'api\module\path\Constant','Type'=>'DYNAMIC');
    public static $RoleTask = array('Name'=>'RoleTask','Route'=>'api\module\roletask\RoleTask','ConstRoute'=>'api\module\roletask\Constant','Type'=>'DYNAMIC');
    public static $RoleTaskLog = array('Name'=>'RoleTaskLog','Route'=>'api\module\roletasklog\RoleTaskLog','ConstRoute'=>'api\module\roletasklog\Constant','Type'=>'DYNAMIC');
    public static $RoleTaskGoal = array('Name'=>'RoleTaskGoal','Route'=>'api\module\roletaskgoal\RoleTaskGoal','ConstRoute'=>'api\module\roletaskgoal\Constant','Type'=>'DYNAMIC');
    public static $RoleTech = array('Name'=>'RoleTech','Route'=>'api\module\roletech\RoleTech','ConstRoute'=>'api\module\roletech\Constant','Type'=>'DYNAMIC');
    public static $Battle = array('Name'=>'Battle','Route'=>'api\module\battle\Battle','ConstRoute'=>'api\module\battle\Constant','Type'=>'DYNAMIC');
    public static $RoleItem = array('Name'=>'RoleItem','Route'=>'api\module\roleitem\RoleItem','ConstRoute'=>'api\module\roleitem\Constant','Type'=>'DYNAMIC');
    public static $ClientThrift = array('Name'=>'ClientThrift','Route'=>'api\module\clientthrift\Client','ConstRoute'=>'api\module\clientthrift\Constant','Type'=>'DYNAMIC');
    public static $Mail = array('Name'=>'Mail','Route'=>'api\module\mail\Mail','ConstRoute'=>'api\module\mail\Constant','Type'=>'DYNAMIC');
    public static $MailBack = array('Name'=>'MailBack','Route'=>'api\module\mailback\MailBack','ConstRoute'=>'api\module\mailback\Constant','Type'=>'DYNAMIC');
    public static $RoleSatellite = array('Name'=>'RoleSatellite','Route'=>'api\module\rolesatellite\RoleSatellite','ConstRoute'=>'api\module\rolesatellite\Constant','Type'=>'DYNAMIC');
    public static $SatelliteForm = array('Name'=>'SatelliteForm','Route'=>'api\module\satelliteform\SatelliteForm','ConstRoute'=>'api\module\satelliteform\Constant','Type'=>'DYNAMIC');
    public static $League = array('Name'=>'League','Route'=>'api\module\league\League','ConstRoute'=>'api\module\league\Constant','Type'=>'DYNAMIC');
    public static $Friend = array('Name'=>'Friend','Route'=>'api\module\friend\Friend','ConstRoute'=>'api\module\friend\Constant','Type'=>'DYNAMIC');
    public static $RoleCommodity = array('Name'=>'RoleCommodity','Route'=>'api\module\rolecommodity\RoleCommodity','ConstRoute'=>'api\module\rolecommodity\Constant','Type'=>'DYNAMIC');
    public static $Vip = array('Name'=>'Vip','Route'=>'api\module\vip\Vip','ConstRoute'=>'api\module\vip\Constant','Type'=>'DYNAMIC');
    public static $Online = array('Name'=>'Online','Route'=>'api\module\online\Online','ConstRoute'=>'api\module\online\Constant','Type'=>'DYNAMIC');
    public static $Recharge = array('Name'=>'Recharge','Route'=>'api\module\recharge\Recharge','ConstRoute'=>'api\module\recharge\Constant','Type'=>'DYNAMIC');
    public static $RoleScreening = array('Name'=>'RoleScreeening','Route'=>'api\module\rolescreening\RoleScreening','ConstRoute'=>'api\module\rolescreening\Constant','Type'=>'DYNAMIC');
    public static $RoleElite = array('Name'=>'RoleElite','Route'=>'api\module\roleelite\RoleElite','ConstRoute'=>'api\module\roleelite\Constant','Type'=>'DYNAMIC');
    public static $RoleCounter = array('Name'=>'RoleCounter','Route'=>'api\module\rolecounter\RoleCounter','ConstRoute'=>'api\module\rolecounter\Constant','Type'=>'DYNAMIC');
    public static $KeyWord = array('Name'=>'KeyWord','Route'=>'api\module\keyword\KeyWord','ConstRoute'=>'api\module\keyword\Constant','Type'=>'DYNAMIC');
    public static $RoleOnlineAward = array('Name'=>'RoleOnlineAward','Route'=>'api\module\roleonlineaward\RoleOnlineAward','ConstRoute'=>'api\module\roleonlineaward\Constant','Type'=>'DYNAMIC');
    public static $RoleCaptain = array('Name'=>'RoleCaptain','Route'=>'api\module\rolecaptain\RoleCaptain','ConstRoute'=>'api\module\rolecaptain\Constant','Type'=>'DYNAMIC');
    public static $RoleSolarExplore = array('Name'=>'RoleSolarExplore','Route'=>'api\module\rolesolarexplore\RoleSolarExplore','ConstRoute'=>'api\module\rolesolarexplore\Constant','Type'=>'DYNAMIC');
    public static $RoleDrop = array('Name'=>'RoleDrop','Route'=>'api\module\roledrop\RoleDrop','ConstRoute'=>'api\module\roledrop\Constant','Type'=>'DYNAMIC');
    public static $RoleSkill = array('Name'=>'RoleSkill','Route'=>'api\module\roleskill\RoleSkill','ConstRoute'=>'api\module\roleskill\Constant','Type'=>'DYNAMIC');
    public static $ActionLog = array('Name'=>'ActionLog','Route'=>'api\module\actionlog\ActionLog','ConstRoute'=>'api\module\actionlog\Constant','Type'=>'DYNAMIC');
    public static $RoleLiveness = array('Name'=>'RoleLiveness','Route'=>'api\module\roleliveness\RoleLiveness','ConstRoute'=>'api\module\roleliveness\Constant','Type'=>'DYNAMIC');
    public static $IcLog = array('Name'=>'IcLog','Route'=>'api\module\accountbook\iclog\IcLog','ConstRoute'=>'api\module\accountbook\iclog\Constant','Type'=>'DYNAMIC');
    public static $MaterialLog = array('Name'=>'MaterialLog','Route'=>'api\module\accountbook\materiallog\MaterialLog','ConstRoute'=>'api\module\accountbook\materiallog\Constant','Type'=>'DYNAMIC');
    public static $ActivityLog = array('Name'=>'ActivityLog','Route'=>'api\module\activitylog\ActivityLog','ConstRoute'=>'api\module\activitylog\Constant','Type'=>'DYNAMIC');
    public static $GuideRecord = array('Name'=>'GuideRecord','Route'=>'api\module\guiderecord\GuideRecord','ConstRoute'=>'api\module\guiderecord\Constant','Type'=>'DYNAMIC');
    public static $UiOpen = array('Name'=>'UiOpen','Route'=>'api\module\uiopen\UiOpen','ConstRoute'=>'api\module\uiopen\Constant','Type'=>'DYNAMIC');
    public static $BattleLog = array('Name'=>'BattleLog','Route'=>'api\module\battle\battlelog\BattleLog','ConstRoute'=>'api\module\battle\battlelog\Constant','Type'=>'DYNAMIC');
    public static $RoleRegularCd = array('Name'=>'RoleRegularCd','Route'=>'api\module\roleregularcd\RoleRegularCd','ConstRoute'=>'api\module\roleregularcd\Constant','Type'=>'DYNAMIC');
    public static $CbtOne = array('Name'=>'CbtOne','Route'=>'api\module\cbtone\CbtOne','ConstRoute'=>'api\module\cbtone\Constant','Type'=>'DYNAMIC');
    public static $RoleShipResearch = array('Name'=>'RoleShipResearch','Route'=>'api\module\roleshipresearch\RoleShipResearch','ConstRoute'=>'api\module\roleshipresearch\Constant','Type'=>'DYNAMIC');
    public static $RankingList = array('Name'=>'RankingList','Route'=>'api\module\rankinglist\RankingList','ConstRoute'=>'api\module\rankinglist\Constant','Type'=>'DYNAMIC');
    public static $LootingLog = array('Name'=>'LootingLog','Route'=>'api\module\battle\lootinglog\LootingLog','ConstRoute'=>'api\module\battle\lootinglog\Constant','Type'=>'DYNAMIC');
    public static $RoleExchange = array('Name'=>'RoleExchange','Route'=>'api\module\roleexchange\RoleExchange','ConstRoute'=>'api\module\roleexchange\Constant','Type'=>'DYNAMIC');
    public static $SystemRecord = array('Name'=>'SystemRecord','Route'=>'api\module\systemrecord\SystemRecord','ConstRoute'=>'api\module\systemrecord\Constant','Type'=>'DYNAMIC');
    public static $DyEffect = array('Name'=>'DyEffect','Route'=>'api\module\dyeffect\DyEffect','ConstRoute'=>'api\module\dyeffect\Constant','Type'=>'DYNAMIC');
    public static $VirtualLooting = array('Name'=>'VirtualLooting','Route'=>'api\module\virtuallooting\VirtualLooting','ConstRoute'=>'api\module\virtuallooting\Constant','Type'=>'DYNAMIC');
    public static $RoleDebris = array('Name'=>'RoleDebris','Route'=>'api\module\roledebris\RoleDebris','ConstRoute'=>'api\module\roledebris\Constant','Type'=>'DYNAMIC');
    public static $RoleDiscount = array('Name'=>'RoleDiscount','Route'=>'api\module\rolediscount\RoleDiscount','ConstRoute'=>'api\module\rolediscount\Constant','Type'=>'DYNAMIC');
    public static $RoleSign = array('Name'=>'RoleSign','Route'=>'api\module\rolesign\RoleSign','ConstRoute'=>'api\module\rolesign\Constant','Type'=>'DYNAMIC');
    public static $ItemLog = array('Name'=>'ItemLog','Route'=>'api\module\accountbook\itemlog\ItemLog','ConstRoute'=>'api\module\accountbook\itemlog\Constant','Type'=>'DYNAMIC');
    public static $RankingLog = array('Name'=>'RankingLog','Route'=>'api\module\rankinglog\RankingLog','ConstRoute'=>'api\module\rankinglog\Constant','Type'=>'DYNAMIC');
    public static $BattleField = array('Name'=>'BattleField','Route'=>'api\module\battlefield\BattleField','ConstRoute'=>'api\module\battlefield\Constant','Type'=>'DYNAMIC');
    public static $BattleQueue = array('Name'=>'BattleQueue','Route'=>'api\module\battlequeue\BattleQueue','ConstRoute'=>'api\module\battlequeue\Constant','Type'=>'DYNAMIC');
    public static $BossDkp = array('Name'=>'BossDkp','Route'=>'api\module\battle\bossdkp\BossDkp','ConstRoute'=>'api\module\battle\bossdkp\Constant','Type'=>'DYNAMIC');
    public static $DyBoss = array('Name'=>'DyBoss','Route'=>'api\module\dyboss\DyBoss','ConstRoute'=>'api\module\dyboss\Constant','Type'=>'DYNAMIC');
    public static $Base = array('Name'=>'Base','Route'=>'api\module\base\Base','ConstRoute'=>'api\module\base\Constant','Type'=>'DYNAMIC');
    public static $BaseBuilding = array('Name'=>'BaseBuilding','Route'=>'api\module\base\basebuilding\BaseBuilding','ConstRoute'=>'api\module\base\basebuilding\Constant','Type'=>'DYNAMIC');
    public static $BaseSatForm = array('Name'=>'BaseSatForm','Route'=>'api\module\base\basesatform\BaseSatForm','ConstRoute'=>'api\module\base\basesatform\Constant','Type'=>'DYNAMIC');
    public static $BaseSat = array('Name'=>'BaseSat','Route'=>'api\module\base\basesat\BaseSat','ConstRoute'=>'api\module\base\basesat\Constant','Type'=>'DYNAMIC');
    public static $RoleCreditLog=array('Name'=>'RoleCreditLog','Route'=>'api\module\rolecreditlog\RoleCreditLog','ConstRoute'=>'api\module\rolecreditlog\Constant','Type'=>'DYNAMIC');
    public static $RoleChip = array('Name'=>'RoleChip','Route'=>'api\module\rolechip\RoleChip','ConstRoute'=>'api\module\rolechip\Constant','Type'=>'DYNAMIC');
    public static $RoleTrials = array('Name'=>'RoleTrials','Route'=>'api\module\roletrials\RoleTrials','ConstRoute'=>'api\module\roletrials\Constant','Type'=>'DYNAMIC');
    public static $RoleExercise = array('Name'=>'RoleExercise','Route'=>'api\module\roleexercise\RoleExercise','ConstRoute'=>'api\module\roleexercise\Constant','Type'=>'DYNAMIC');
    public static $RoleDegree = array('Name'=>'RoleDegree','Route'=>'api\module\roledegree\RoleDegree','ConstRoute'=>'api\module\roledegree\Constant','Type'=>'DYNAMIC');
    public static $ChipLog = array('Name'=>'ChipLog','Route'=>'api\module\accountbook\chiplog\ChipLog','ConstRoute'=>'api\module\accountbook\chiplog\Constant','Type'=>'DYNAMIC');
    public static $Stronghold = array('Name'=>'Stronghold','Route'=>'api\module\gameplanet\Stronghold','ConstRoute'=>'api\module\gameplanet\stronghold\Constant','Type'=>'DYNAMIC');
    public static $AStargate = array('Name'=>'AStargate','Route'=>'api\module\gameplanet\AStargate','ConstRoute'=>'api\module\gameplanet\astargate\Constant','Type'=>'DYNAMIC');
    public static $StrongholdActivity = array('Name'=>'StrongholdActivity','Route'=>'api\module\strongholdactivity\StrongholdActivity','ConstRoute'=>'api\module\strongholdactivity\Constant','Type'=>'DYNAMIC');
    public static $StrongholdRoleDkp = array('Name'=>'StrongholdRoleDkp','Route'=>'api\module\strongholdroledkp\StrongholdRoleDkp','ConstRoute'=>'api\module\strongholdroledkp\Constant','Type'=>'DYNAMIC');
    public static $Hatter = array('Name'=>'Hatter','Route'=>'api\module\hatter\Hatter','ConstRoute'=>'api\module\hatter\Constant','Type'=>'DYNAMIC');
    public static $RoleMailLog = array('Name'=>'Hatter','Route'=>'api\module\rolemaillog\RoleMailLog','ConstRoute'=>'api\module\rolemaillog\Constant','Type'=>'DYNAMIC');
    public static $RandExchange = array('Name'=>'RandExchange','Route'=>'api\module\randexchange\RandExchange','ConstRoute'=>'api\module\randexchange\Constant','Type'=>'DYNAMIC');
    public static $ArenaRewardLog = array('Name'=>'ArenaRewardLog','Route'=>'api\module\arenarewardlog\ArenaRewardLog','ConstRoute'=>'api\module\arenarewardlog\Constant','Type'=>'DYNAMIC');
    public static $ShipLog = array('Name'=>'ShipLog','Route'=>'api\module\accountbook\shiplog\ShipLog','ConstRoute'=>'api\module\accountbook\shiplog\Constant','Type'=>'DYNAMIC');
    public static $ChallengeRewardLog = array('Name'=>'ChallengeRewardLog','Route'=>'api\module\challengerewardlog\ChallengeRewardLog','ConstRoute'=>'api\module\challengerewardlog\Constant','Type'=>'DYNAMIC');
    public static $RoleScenes = array('Name'=>'RoleScenes','Route'=>'api\module\rolescenes\RoleScenes','ConstRoute'=>'api\module\rolescenes\Constant','Type'=>'DYNAMIC');
    public static $RoleTeam = array('Name'=>'RoleTeam','Route'=>'api\module\roleteam\RoleTeam','ConstRoute'=>'api\module\roleteam\Constant','Type'=>'DYNAMIC');
    public static $RoleBindTeam = array('Name'=>'RoleBindTeam','Route'=>'api\module\rolebindteam\RoleBindTeam','ConstRoute'=>'api\module\rolebindteam\Constant','Type'=>'DYNAMIC');
    public static $RoleCoin = array('Name'=>'RoleCoin','Route'=>'api\module\rolecoin\RoleCoin','ConstRoute'=>'api\module\rolecoin\Constant','Type'=>'DYNAMIC');
    public static $Business = array('Name'=>'Business','Route'=>'api\module\business\Business','ConstRoute'=>'api\module\business\Constant','Type'=>'DYNAMIC');
    public static $FleetMirror = array('Name'=>'FleetMirror','Route'=>'api\module\fleetmirror\FleetMirror','ConstRoute'=>'api\module\fleetmirror\Constant','Type'=>'DYNAMIC');
    public static $PlanetDefend = array('Name'=>'PlanetDefend','Route'=>'api\module\planetdefend\PlanetDefend','ConstRoute'=>'api\module\planetdefend\Constant','Type'=>'DYNAMIC');
    public static $PlanetDefendPos = array('Name'=>'PlanetDefendPos','Route'=>'api\module\planetdefendpos\PlanetDefendPos','ConstRoute'=>'api\module\planetdefendpos\Constant','Type'=>'DYNAMIC');
    public static $FortunateActivity = array('Name'=>'FortunateActivity','Route'=>'api\module\fortunateactivity\FortunateActivity','ConstRoute'=>'api\module\fortunateactivity\Constant','Type'=>'DYNAMIC');
    public static $RoleFortunate = array('Name'=>'RoleFortunate','Route'=>'api\module\rolefortunate\RoleFortunate','ConstRoute'=>'api\module\rolefortunate\Constant','Type'=>'DYNAMIC');
    public static $ActivityExchange = array('Name'=>'ActivityExchange','Route'=>'api\module\activityexchange\ActivityExchange','ConstRoute'=>'api\module\activityexchange\Constant','Type'=>'DYNAMIC');
    public static $FortunateLog = array('Name'=>'FortunateLog','Route'=>'api\module\fortunatelog\FortunateLog','ConstRoute'=>'api\module\fortunatelog\Constant','Type'=>'DYNAMIC');
    public static $RoleUserAward = array('Name'=>'RoleUserAward','Route'=>'api\module\roleuseraward\RoleUserAward','ConstRoute'=>'api\module\roleuseraward\Constant','Type'=>'DYNAMIC');
    public static $BaseLog = array('Name'=>'BaseLog','Route'=>'api\module\accountbook\baselog\BaseLog','ConstRoute'=>'api\module\accountbook\baselog\Constant','Type'=>'DYNAMIC');
    public static $Convene = array('Name'=>'Convene','Route'=>'api\module\convene\Convene','ConstRoute'=>'api\module\convene\Constant','Type'=>'DYNAMIC');
    public static $ConveneLog = array('Name'=>'ConveneLog','Route'=>'api\module\convenelog\ConveneLog','ConstRoute'=>'api\module\convenelog\Constant','Type'=>'DYNAMIC');
    public static $DefendLog = array('Name'=>'DefendLog','Route'=>'api\module\defendlog\DefendLog','ConstRoute'=>'api\module\defendlog\Constant','Type'=>'DYNAMIC');
    public static $SlotMachine = array('Name'=>'SlotMachine','Route'=>'api\module\slotmachine\SlotMachine','ConstRoute'=>'api\module\slotmachine\Constant','Type'=>'DYNAMIC');
    public static $RoleSlotMachine = array('Name'=>'RoleSlotMachine','Route'=>'api\module\roleslotmachine\RoleSlotMachine','ConstRoute'=>'api\module\roleslotmachine\Constant','Type'=>'DYNAMIC');
    public static $SlotMachineLog = array('Name'=>'SlotMachineLog','Route'=>'api\module\slotmachinelog\SlotMachineLog','ConstRoute'=>'api\module\slotmachinelog\Constant','Type'=>'DYNAMIC');
    public static $SkyLevelLog = array('Name'=>'SkyLevelLog','Route'=>'api\module\skylevellog\SkyLevelLog','ConstRoute'=>'api\module\skylevellog\Constant','Type'=>'DYNAMIC');
    public static $ActivityBox = array('Name'=>'ActivityBox','Route'=>'api\module\activitybox\ActivityBox','ConstRoute'=>'api\module\activitybox\Constant','Type'=>'DYNAMIC');
    public static $RoleActivityBox = array('Name'=>'RoleActivityBox','Route'=>'api\module\roleactivitybox\RoleActivityBox','ConstRoute'=>'api\module\roleactivitybox\Constant','Type'=>'DYNAMIC');
    public static $ActivityBoxLog = array('Name'=>'ActivityBoxLog','Route'=>'api\module\activityboxlog\ActivityBoxLog','ConstRoute'=>'api\module\activityboxlog\Constant','Type'=>'DYNAMIC');
    public static $MaterialDetailLog = array('Name'=>'MaterialDetailLog','Route'=>'api\module\accountbook\materialdetaillog\MaterialDetailLog','ConstRoute'=>'api\module\accountbook\materialdetaillog\Constant','Type'=>'DYNAMIC');
    public static $RoleSHWeek = array('Name'=>'RoleSHWeek','Route'=>'api\module\roleshweek\RoleSHWeek','ConstRoute'=>'api\module\roleshweek\Constant','Type'=>'DYNAMIC');
    public static $ShAwardLog = array('Name'=>'ShAwardLog','Route'=>'api\module\shawardlog\ShAwardLog','ConstRoute'=>'api\module\shawardlog\Constant','Type'=>'DYNAMIC');
    public static $RoleFormation = array('Name'=>'RoleFormation','Route'=>'api\module\roleformation\RoleFormation','ConstRoute'=>'api\module\roleformation\Constant','Type'=>'DYNAMIC');
    public static $DySolar = array('Name'=>'DySolar','Route'=>'api\module\dysolar\DySolar','ConstRoute'=>'api\module\dysolar\Constant','Type'=>'DYNAMIC');
    public static $RoleBuildItem = array('Name'=>'RoleBuildItem','Route'=>'api\module\rolebuilditem\RoleBuildItem','ConstRoute'=>'api\module\rolebuilditem\Constant','Type'=>'DYNAMIC');
    public static $RoleGear = array('Name'=>'RoleGear','Route'=>'api\module\rolegear\RoleGear','ConstRoute'=>'api\module\rolegear\Constant','Type'=>'DYNAMIC');
    public static $VirtualFleet = array('Name'=>'VirtualFleet','Route'=>'api\module\virtualfleet\VirtualFleet','ConstRoute'=>'api\module\virtualfleet\Constant','Type'=>'DYNAMIC');
    public static $VirtualRoleFleet = array('Name'=>'VirtualRoleFleet','Route'=>'api\module\virtualrolefleet\VirtualRoleFleet','ConstRoute'=>'api\module\virtualrolefleet\Constant','Type'=>'DYNAMIC');
    public static $ArenaRole = array('Name'=>'ArenaRole','Route'=>'api\module\arenarole\ArenaRole','ConstRoute'=>'api\module\arenarole\Constant','Type'=>'DYNAMIC');
    public static $ArenaRanking = array('Name'=>'ArenaRanking','Route'=>'api\module\arenaranking\ArenaRanking','ConstRoute'=>'api\module\arenaranking\Constant','Type'=>'DYNAMIC');
    public static $ArenaRecord = array('Name'=>'ArenaRecord','Route'=>'api\module\arenarecord\ArenaRecord','ConstRoute'=>'api\module\arenarecord\Constant','Type'=>'DYNAMIC');
    public static $RoleExpeditionZone = array('Name'=>'RoleExpeditionZone','Route'=>'api\module\roleexpeditionzone\RoleExpeditionZone','ConstRoute'=>'api\module\roleexpeditionzone\Constant','Type'=>'DYNAMIC');
    public static $RoleRuins = array('Name'=>'RoleRuins','Route'=>'api\module\roleruins\RoleRuins','ConstRoute'=>'api\module\roleruins\Constant','Type'=>'DYNAMIC');
    public static $RoleRuinsLog = array('Name'=>'RoleRuinsLog','Route'=>'api\module\roleruinslog\RoleRuinsLog','ConstRoute'=>'api\module\roleruinslog\Constant','Type'=>'DYNAMIC');
    public static $StrongholdBuff = array('Name'=>'StrongholdBuff','Route'=>'api\module\strongholdbuff\StrongholdBuff','ConstRoute'=>'api\module\strongholdbuff\Constant','Type'=>'DYNAMIC');
    public static $StrongholdBattleLog = array('Name'=>'StrongholdBattleLog','Route'=>'api\module\strongholdbattlelog\StrongholdBattleLog','ConstRoute'=>'api\module\strongholdbattlelog\Constant','Type'=>'DYNAMIC');
    public static $RechargeLogTx = array('Name'=>'RechargeLogTx','Route'=>'api\module\rechargelogtx\RechargeLogTx','ConstRoute'=>'api\module\rechargelogtx\Constant','Type'=>'DYNAMIC');
    public static $RoleStarShipRemake = array('Name'=>'RoleStarShipRemake','Route'=>'api\module\rolestarshipremake\RoleStarShipRemake','ConstRoute'=>'api\module\rolestarshipremake\Constant','Type'=>'DYNAMIC');
    public static $RoleDetection = array('Name'=>'RoleDetection','Route'=>'api\module\roledetection\RoleDetection','ConstRoute'=>'api\module\roledetection\Constant','Type'=>'DYNAMIC');
    public static $RoleDetectionTask = array('Name'=>'RoleDetectionTask','Route'=>'api\module\roledetectiontask\RoleDetectionTask','ConstRoute'=>'api\module\roledetectiontask\Constant','Type'=>'DYNAMIC');
    public static $RoleLotery = array('Name'=>'RoleLotery','Route'=>'api\module\rolelotery\RoleLotery','ConstRoute'=>'api\module\rolelotery\Constant','Type'=>'DYNAMIC');
    public static $RoleServerGoal = array('Name'=>'RoleServerGoal','Route'=>'api\module\roleservergoal\RoleServerGoal','ConstRoute'=>'api\module\roleservergoal\Constant','Type'=>'DYNAMIC');
    public static $RaiderArkDy = array('Name'=>'RaiderArkDy','Route'=>'api\module\raiderarkdy\RaiderArkDy','ConstRoute'=>'api\module\raiderarkdy\Constant','Type'=>'DYNAMIC');
    public static $RaiderArkArea = array('Name'=>'RaiderArkArea','Route'=>'api\module\raiderarkarea\RaiderArkArea','ConstRoute'=>'api\module\raiderarkarea\Constant','Type'=>'DYNAMIC');
    public static $RaiderArkCredits = array('Name'=>'RaiderArkCredits','Route'=>'api\module\raiderarkcredits\RaiderArkCredits','ConstRoute'=>'api\module\raiderarkcredits\Constant','Type'=>'DYNAMIC');
    public static $RaiderArkReport = array('Name'=>'RaiderArkReport','Route'=>'api\module\raiderarkreport\RaiderArkReport','ConstRoute'=>'api\module\raiderarkreport\Constant','Type'=>'DYNAMIC');
    public static $RoleHonorMedal = array('Name'=>'RoleHonorMedal','Route'=>'api\module\rolehonormedal\RoleHonorMedal','ConstRoute'=>'api\module\rolehonormedal\Constant','Type'=>'DYNAMIC');
    public static $RoleHonorMedalPro = array('Name'=>'RoleHonorMedalPro','Route'=>'api\module\rolehonormedalpro\RoleHonorMedalPro','ConstRoute'=>'api\module\rolehonormedalpro\Constant','Type'=>'DYNAMIC');
    public static $RoleHFrontLine = array('Name'=>'RoleHFrontLine','Route'=>'api\module\rolehfrontline\RoleHFrontLine','ConstRoute'=>'api\module\rolehfrontline\Constant','Type'=>'DYNAMIC');
    public static $BroadCast = array('Name'=>'BroadCast','Route'=>'api\module\broadcast\BroadCast','ConstRoute'=>'api\module\broadcast\Constant','Type'=>'DYNAMIC');
    public static $RefineReport = array('Name'=>'RefineReport','Route'=>'api\module\refinereport\RefineReport','ConstRoute'=>'api\module\refinereport\Constant','Type'=>'DYNAMIC');
    public static $DeathBattle = array('Name'=>'DeathBattle','Route'=>'api\module\deathbattle\DeathBattle','ConstRoute'=>'api\module\deathbattle\Constant','Type'=>'DYNAMIC');
    public static $DeathBattleReport = array('Name'=>'DeathBattleReport','Route'=>'api\module\deathbattlereport\DeathBattleReport','ConstRoute'=>'api\module\deathbattlereport\Constant','Type'=>'DYNAMIC');
    public static $RoleSolarScreening = array('Name'=>'RoleSolarScreening','Route'=>'api\module\rolesolarscreening\RoleSolarScreening','ConstRoute'=>'api\module\rolesolarscreening\Constant','Type'=>'DYNAMIC');
    public static $Fighter = array('Name'=>'Fighter','Route'=>'api\module\fighter\Fighter','ConstRoute'=>'api\module\fighter\Constant','Type'=>'DYNAMIC');
    public static $FighterLog = array('Name'=>'FighterLog','Route'=>'api\module\accountbook\fighterlog\FighterLog','ConstRoute'=>'api\module\accountbook\fighterlog\Constant','Type'=>'DYNAMIC');

    //cross
    public static $ArenaShip = array('Name'=>'ArenaShip','Route'=>'cmodule\arenaship\ArenaShip','ConstRoute'=>'cmodule\arenaship\Constant','Type'=>'DYNAMIC');
    public static $ChallengeRole = array('Name'=>'ChallengeRole','Route'=>'cmodule\challengerole\ChallengeRole','ConstRoute'=>'cmodule\challengerole\Constant','Type'=>'DYNAMIC');
    public static $ChallengeFleet = array('Name'=>'ChallengeFleet','Route'=>'cmodule\challengefleet\ChallengeFleet','ConstRoute'=>'cmodule\challengefleet\Constant','Type'=>'DYNAMIC');
    public static $Challenge = array('Name'=>'Challenge','Route'=>'cmodule\challenge\Challenge','ConstRoute'=>'cmodule\challenge\Constant','Type'=>'DYNAMIC');
    public static $CRoleCounter = array('Name'=>'CRoleCounter','Route'=>'cmodule\crolecounter\CRoleCounter','ConstRoute'=>'cmodule\crolecounter\Constant','Type'=>'DYNAMIC');
    public static $CrossRole = array('Name'=>'CrossRole','Route'=>'cmodule\crossrole\CrossRole','ConstRoute'=>'cmodule\crossrole\Constant','Type'=>'DYNAMIC');
    public static $CrossFleet = array('Name'=>'CrossFleet','Route'=>'cmodule\crossfleet\CrossFleet','ConstRoute'=>'cmodule\crossfleet\Constant','Type'=>'DYNAMIC');
    public static $StrongholdCrossDkp = array('Name'=>'StrongholdCrossDkp','Route'=>'cmodule\strongholdcrossdkp\StrongholdCrossDkp','ConstRoute'=>'cmodule\strongholdcrossdkp\Constant','Type'=>'DYNAMIC');
    public static $StrongholdScore = array('Name'=>'StrongholdScore','Route'=>'cmodule\strongholdscore\StrongholdScore','ConstRoute'=>'cmodule\strongholdscore\Constant','Type'=>'DYNAMIC');
    public static $StrongholdNotice = array('Name'=>'StrongholdNotice','Route'=>'cmodule\strongholdnotice\StrongholdNotice','ConstRoute'=>'cmodule\strongholdnotice\Constant','Type'=>'DYNAMIC');
    public static $CrossItem = array('Name'=>'CrossItem','Route'=>'cmodule\crossitem\CrossItem','ConstRoute'=>'cmodule\crossitem\Constant','Type'=>'DYNAMIC');
    public static $StrongholdAwardLog = array('Name'=>'StrongholdAwardLog','Route'=>'cmodule\strongholdawardlog\StrongholdAwardLog','ConstRoute'=>'cmodule\strongholdawardlog\Constant','Type'=>'DYNAMIC');

    // SYS
    public static $ExerciseChapter = array('Name'=>'ExerciseChapter','Route'=>'sys\exercisechapter\ExerciseChapter','ConstRoute'=>'sys\exercisechapter\Constant','Type'=>'SYS');
    public static $ExerciseScreening = array('Name'=>'ExerciseScreening','Route'=>'sys\exercisescreening\ExerciseScreening','ConstRoute'=>'sys\exercisescreening\Constant','Type'=>'SYS');
    public static $Action = array('Name'=>'Action','Route'=>'sys\action\Action','ConstRoute'=>'sys\action\Constant','Type'=>'SYS');
    public static $Avatar = array('Name'=>'Avatar','Route'=>'sys\avatar\Avatar','ConstRoute'=>'sys\avatar\Constant','Type'=>'SYS');
    public static $BannedWord = array('Name'=>'BannedWord','Route'=>'sys\bannedword\BannedWord','ConstRoute'=>'sys\bannedword\Constant','Type'=>'SYS');
    public static $Building = array('Name'=>'Building','Route'=>'sys\building\Building','ConstRoute'=>'sys\building\Constant','Type'=>'SYS');
    public static $Commodity = array('Name'=>'Commodity','Route'=>'sys\commodity\Commodity','ConstRoute'=>'sys\commodity\Constant','Type'=>'SYS');
    public static $EventSet = array('Name'=>'EventSet','Route'=>'sys\eventset\EventSet','ConstRoute'=>'sys\eventset\Constant','Type'=>'SYS');
    public static $Faction = array('Name'=>'Faction','Route'=>'sys\faction\Faction','ConstRoute'=>'sys\faction\Constant','Type'=>'SYS');
    public static $Galaxy = array('Name'=>'Galaxy','Route'=>'sys\galaxy\Galaxy','ConstRoute'=>'sys\galaxy\Constant','Type'=>'SYS');
    public static $GalaxyPath = array('Name'=>'GalaxyPath','Route'=>'sys\galaxypath\GalaxyPath','ConstRoute'=>'sys\galaxypath\Constant','Type'=>'SYS');
    public static $GameSetting = array('Name'=>'GameSetting','Route'=>'sys\gamesetting\GameSetting','ConstRoute'=>'sys\gamesetting\Constant','Type'=>'SYS');
    public static $Item = array('Name'=>'Item','Route'=>'sys\item\Item','ConstRoute'=>'sys\item\Constant','Type'=>'SYS');
    public static $Planet = array('Name'=>'Planet','Route'=>'sys\planet\Planet','ConstRoute'=>'sys\planet\Constant','Type'=>'SYS');
    public static $RoleLevel = array('Name'=>'RoleLevel','Route'=>'sys\rolelevel\RoleLevel','ConstRoute'=>'sys\rolelevel\Constant','Type'=>'SYS');
    public static $Server = array('Name'=>'Server','Route'=>'sys\server\Server','ConstRoute'=>'sys\server\Constant','Type'=>'SYS');
    public static $Solar = array('Name'=>'Solar','Route'=>'sys\solar\Solar','ConstRoute'=>'sys\solar\Constant','Type'=>'SYS');
    public static $StarShip = array('Name'=>'StarShip','Route'=>'sys\starship\StarShip','ConstRoute'=>'sys\starship\Constant','Type'=>'SYS');
    public static $Task = array('Name'=>'Task','Route'=>'sys\task\Task','ConstRoute'=>'sys\task\Constant','Type'=>'SYS');
    public static $TaskGoal = array('Name'=>'TaskGoal','Route'=>'sys\taskgoal\TaskGoal','ConstRoute'=>'sys\taskgoal\Constant','Type'=>'SYS');
    public static $TaskSerial = array('Name'=>'TaskSerial','Route'=>'sys\taskserial\TaskSerial','ConstRoute'=>'sys\taskserial\Constant','Type'=>'SYS');
    public static $Tech = array('Name'=>'Tech','Route'=>'sys\tech\Tech','ConstRoute'=>'sys\tech\Constant','Type'=>'SYS');
    public static $TechEffectType = array('Name'=>'TechEffectType','Route'=>'sys\techeffecttype\TechEffectType','ConstRoute'=>'sys\techeffecttype\Constant','Type'=>'SYS');
    public static $Mob = array('Name'=>'Mob' ,'Route'=>'sys\mob\Mob','ConstRoute'=>'sys\mob\Constant', 'Type'=>'SYS');
    public static $MobFleet = array('Name'=>'MobFleet','Route'=>'sys\mobfleet\MobFleet','ConstRoute'=>'sys\mobfleet\Constant','Type'=>'SYS');
    public static $Lair = array('Name'=>'Lair','Route'=>'sys\lair\Lair','ConstRoute'=>'sys\lair\Constant','Type'=>'SYS');
    public static $ArenaLair = array('Name'=>'ArenaLair','Route'=>'sys\arenalair\ArenaLair','ConstRoute'=>'sys\arenalair\Constant','Type'=>'SYS');
    public static $Skill = array('Name'=>'Skill','Route'=>'sys\skill\Skill','ConstRoute'=>'sys\skill\Constant','Type'=>'SYS');
    public static $Satellite = array('Name'=>'Satellite','Route'=>'sys\satellite\Satellite','ConstRoute'=>'sys\satellite\Constant','Type'=>'SYS');
    public static $PowerAct = array('Name'=>'PowerAct','Route'=>'sys\poweract\PowerAct','ConstRoute'=>'sys\poweract\Constant','Type'=>'SYS');
    public static $LeaguePower = array('Name'=>'LeaguePower','Route'=>'sys\leaguepower\LeaguePower','ConstRoute'=>'sys\leaguepower\Constant','Type'=>'SYS');
    public static $VipExp = array('Name'=>'VipExp','Route'=>'sys\vipexp\VipExp','ConstRoute'=>'sys\vipexp\Constant','Type'=>'SYS');
    public static $VipFunc = array('Name'=>'VipFunc','Route'=>'sys\vipfunc\VipFunc','ConstRoute'=>'sys\vipfunc\Constant','Type'=>'SYS');
    public static $VipPower = array('Name'=>'VipPower','Route'=>'sys\vippower\VipPower','ConstRoute'=>'sys\vippower\Constant','Type'=>'SYS');
    public static $VipAward = array('Name'=>'VipAward','Route'=>'sys\vipaward\VipAward','ConstRoute'=>'sys\vipaward\Constant','Type'=>'SYS');
    public static $BuffEffect = array('Name'=>'BuffEffect','Route'=>'sys\buffeffect\BuffEffect','ConstRoute'=>'sys\buffeffect\Constant','Type'=>'SYS');
    public static $GalaxyChapter = array('Name'=>'GalaxyChapter','Route'=>'sys\galaxychapter\GalaxyChapter','ConstRoute'=>'sys\galaxychapter\Constant','Type'=>'SYS');
    public static $SolarScreening = array('Name'=>'SolarScreening','Route'=>'sys\solarscreening\SolarScreening','ConstRoute'=>'sys\solarscreening\Constant','Type'=>'SYS');
    public static $EliteScreening = array('Name'=>'EliteScreening','Route'=>'sys\elitescreening\EliteScreening','ConstRoute'=>'sys\elitescreening\Constant','Type'=>'SYS');
    public static $Counter = array('Name'=>'Counter','Route'=>'sys\counter\Counter','ConstRoute'=>'sys\counter\Constant','Type'=>'SYS');
    public static $OnlineAward = array('Name'=>'OnlineAward','Route'=>'sys\onlineaward\OnlineAward','ConstRoute'=>'sys\onlineaward\Constant','Type'=>'SYS');
    public static $Captain = array('Name'=>'Captain','Route'=>'sys\captain\Captain','ConstRoute'=>'sys\captain\Constant','Type'=>'SYS');
    public static $CaptainLevel = array('Name'=>'CaptainLevel','Route'=>'sys\captainlevel\CaptainLevel','ConstRoute'=>'sys\captainlevel\Constant','Type'=>'SYS');
    public static $CaptainGrade = array('Name'=>'CaptainGrade','Route'=>'sys\captaingrade\CaptainGrade','ConstRoute'=>'sys\captaingrade\Constant','Type'=>'SYS');
    public static $CaptainProperty = array('Name'=>'CaptainProperty','Route'=>'sys\captainproperty\CaptainProperty','ConstRoute'=>'sys\captainproperty\Constant','Type'=>'SYS');
    public static $CaptainAbility = array('Name'=>'CaptainAbility','Route'=>'sys\captainability\CaptainAbility','ConstRoute'=>'sys\captainability\Constant','Type'=>'SYS');
    public static $AwardDrop = array('Name'=>'AwardDrop','Route'=>'sys\awarddrop\AwardDrop','ConstRoute'=>'sys\awarddrop\Constant','Type'=>'SYS');
    public static $MailTemplate = array('Name'=>'MailTemplate','Route'=>'sys\mailtemplate\MailTemplate','ConstRoute'=>'sys\mailtemplate\Constant','Type'=>'SYS');
    public static $Liveness = array('Name'=>'Liveness','Route'=>'sys\liveness\Liveness','ConstRoute'=>'sys\liveness\Constant','Type'=>'SYS');
    public static $LivenessAwards = array('Name'=>'LivenessAwards','Route'=>'sys\livenessawards\LivenessAwards','ConstRoute'=>'sys\livenessawards\Constant','Type'=>'SYS');
    public static $SignAwards = array('Name'=>'SignAwards','Route'=>'sys\signawards\SignAwards','ConstRoute'=>'sys\signawards\Constant','Type'=>'SYS');
    public static $Activity = array('Name'=>'Activity','Route'=>'sys\activity\Activity','ConstRoute'=>'sys\activity\Constant','Type'=>'SYS');
    public static $Synthesize = array('Name'=>'Synthesize','Route'=>'sys\synthesize\Synthesize','ConstRoute'=>'sys\synthesize\Constant','Type'=>'SYS');
    public static $RegularCd = array('Name'=>'RegularCd','Route'=>'sys\regularcd\RegularCd','ConstRoute'=>'sys\regularcd\Constant','Type'=>'SYS');
    public static $Guide = array('Name'=>'Guide','Route'=>'sys\guide\Guide','ConstRoute'=>'sys\guide\Constant','Type'=>'SYS');
    public static $ShipResearch = array('Name'=>'ShipResearch','Route'=>'sys\shipresearch\ShipResearch','ConstRoute'=>'sys\shipresearch\Constant','Type'=>'SYS');
    public static $MilitaryRank = array('Name'=>'MilitaryRank','Route'=>'sys\militaryrank\MilitaryRank','ConstRoute'=>'sys\militaryrank\Constant','Type'=>'SYS');
    public static $ChatTemplate = array('Name'=>'ChatTemplate','Route'=>'sys\chattemplate\ChatTemplate','ConstRoute'=>'sys\chattemplate\Constant','Type'=>'SYS');
    public static $Exchange = array('Name'=>'Exchange','Route'=>'sys\exchange\Exchange','ConstRoute'=>'sys\exchange\Constant','Type'=>'SYS');
    public static $BuildingLevel = array('Name'=>'BuildingLevel','Route'=>'sys\buildinglevel\BuildingLevel','ConstRoute'=>'sys\buildinglevel\Constant','Type'=>'SYS');
    public static $Effect = array('Name'=>'Effect','Route'=>'sys\effect\Effect','ConstRoute'=>'sys\effect\Constant','Type'=>'SYS');
    public static $EffectType = array('Name'=>'EffectType','Route'=>'sys\effecttype\EffectType','ConstRoute'=>'sys\effecttype\Constant','Type'=>'SYS');
    public static $VirtualRole = array('Name'=>'VirtualRole','Route'=>'sys\virtualrole\VirtualRole','ConstRoute'=>'sys\virtualrole\Constant','Type'=>'SYS');
    public static $Language = array('Name'=>'Language','Route'=>'sys\language\Language','ConstRoute'=>'sys\language\Constant','Type'=>'SYS');
    public static $ScreeningStar = array('Name'=>'ScreeningStar','Route'=>'sys\screeningstar\ScreeningStar','ConstRoute'=>'sys\screeningstar\Constant','Type'=>'SYS');
    public static $ActivityAward = array('Name'=>'ActivityAward','Route'=>'sys\activityaward\ActivityAward','ConstRoute'=>'sys\activityaward\Constant','Type'=>'SYS');
    public static $AddUpAwards = array('Name'=>'AddUpAwards','Route'=>'sys\addupawards\AddUpAwards','ConstRoute'=>'sys\addupawards\Constant','Type'=>'SYS');
    public static $RandGoods = array('Name'=>'RandGoods','Route'=>'sys\randgoods\RandGoods','ConstRoute'=>'sys\randgoods\Constant','Type'=>'SYS');
    public static $BattleSet = array('Name'=>'BattleSet','Route'=>'sys\battleset\BattleSet','ConstRoute'=>'sys\battleset\Constant','Type'=>'SYS');
    public static $Boss = array('Name'=>'Boss','Route'=>'sys\boss\Boss','ConstRoute'=>'sys\boss\Constant','Type'=>'SYS');
    public static $BossRanking = array('Name'=>'BossRanking','Route'=>'sys\bossranking\BossRanking','ConstRoute'=>'sys\bossranking\Constant','Type'=>'SYS');
    public static $BossLevel = array('Name'=>'BossLevel','Route'=>'sys\bosslevel\BossLevel','ConstRoute'=>'sys\bosslevel\Constant','Type'=>'SYS');
    public static $ActivityAction=array('Name'=>'ActivityAction','Route'=>'sys\activityaction\ActivityAction','ConstRoute'=>'sys\activityaction\Constant','Type'=>'SYS');
    public static $Chip = array('Name'=>'Chip','Route'=>'sys\chip\Chip','ConstRoute'=>'sys\chip\Constant','Type'=>'SYS');
    public static $ChipLevel = array('Name'=>'ChipLevel','Route'=>'sys\chiplevel\ChipLevel','ConstRoute'=>'sys\chiplevel\Constant','Type'=>'SYS');
    public static $TrialsChapter = array('Name'=>'TrialsChapter','Route'=>'sys\trialschapter\TrialsChapter','ConstRoute'=>'sys\trialschapter\Constant','Type'=>'SYS');
    public static $TrialsScreening = array('Name'=>'TrialsScreening','Route'=>'sys\trialsscreening\TrialsScreening','ConstRoute'=>'sys\trialsscreening\Constant','Type'=>'SYS');
    public static $Degree = array('Name'=>'Degree','Route'=>'sys\degree\Degree','ConstRoute'=>'sys\degree\Constant','Type'=>'SYS');
    public static $GameModule = array('Name'=>'GameModule','Route'=>'sys\gamemodule\GameModule','ConstRoute'=>'sys\gamemodule\Constant','Type'=>'SYS');
    public static $PlanetPath = array('Name'=>'PlanetPath','Route'=>'sys\planetpath\PlanetPath','ConstRoute'=>'sys\planetpath\Constant','Type'=>'SYS');
    public static $SHActivity = array('Name'=>'SHActivity','Route'=>'sys\shactivity\SHActivity','ConstRoute'=>'sys\shactivity\Constant','Type'=>'SYS');
    public static $SHDkpAward = array('Name'=>'SHDkpAward','Route'=>'sys\shdkpaward\SHDkpAward','ConstRoute'=>'sys\shdkpaward\Constant','Type'=>'SYS');
    public static $StrongholdPlanet = array('Name'=>'StrongholdPlanet','Route'=>'sys\strongholdplanet\StrongholdPlanet','ConstRoute'=>'sys\strongholdplanet\Constant','Type'=>'SYS');
    public static $TrialsRankAward = array('Name'=>'TrialsRankAward','Route'=>'sys\trialsrankaward\TrialsRankAward','ConstRoute'=>'sys\trialsrankaward\Constant','Type'=>'SYS');
    public static $StrongholdLair = array('Name'=>'StrongholdLair','Route'=>'sys\strongholdlair\StrongholdLair','ConstRoute'=>'sys\strongholdlair\Constant','Type'=>'SYS');
    public static $Cross = array('Name'=>'Cross','Route'=>'sys\cross\Cross','ConstRoute'=>'sys\cross\Constant','Type'=>'SYS');
    public static $CrossServer = array('Name'=>'CrossServer','Route'=>'sys\crossserver\CrossServer','ConstRoute'=>'sys\crossserver\Constant','Type'=>'SYS');
    public static $ArenaAward = array('Name'=>'ArenaAward','Route'=>'sys\arenaaward\ArenaAward','ConstRoute'=>'sys\arenaaward\Constant','Type'=>'SYS');
    public static $ChallengeAward = array('Name'=>'ChallengeAward','Route'=>'sys\challengeAward\ChallengeAward','ConstRoute'=>'sys\challengeAward\Constant','Type'=>'SYS');
    public static $Scenes = array('Name'=>'Scenes','Route'=>'sys\scenes\Scenes','ConstRoute'=>'sys\scenes\Constant','Type'=>'SYS');
    public static $LeagueLevel = array('Name'=>'LeagueLevel','Route'=>'sys\leaguelevel\LeagueLevel','ConstRoute'=>'sys\leaguelevel\Constant','Type'=>'SYS');
    public static $ActivityProgressive = array('Name'=>'ActivityProgressive','Route'=>'sys\activityprogressive\ActivityProgressive','ConstRoute'=>'sys\activityprogressive\Constant','Type'=>'SYS');
    public static $FortunateAward = array('Name'=>'FortunateAward','Route'=>'sys\fortunateaward\FortunateAward','ConstRoute'=>'sys\fortunateaward\Constant','Type'=>'SYS');
    public static $FortunateRankAward = array('Name'=>'FortunateRankAward','Route'=>'sys\fortunaterankaward\FortunateRankAward','ConstRoute'=>'sys\fortunaterankaward\Constant','Type'=>'SYS');
    public static $ExchangeClass = array('Name'=>'ExchangeClass','Route'=>'sys\exchangeclass\ExchangeClass','ConstRoute'=>'sys\exchangeclass\Constant','Type'=>'SYS');
    public static $UserAward = array('Name'=>'UserAward','Route'=>'sys\useraward\UserAward','ConstRoute'=>'sys\useraward\Constant','Type'=>'SYS');
    public static $UserAwardUser = array('Name'=>'UserAwardUser','Route'=>'sys\userawarduser\UserAwardUser','ConstRoute'=>'sys\userawarduser\Constant','Type'=>'SYS');
    public static $FortunateAwardGroup = array('Name'=>'FortunateAwardGroup','Route'=>'sys\fortunateawardgroup\FortunateAwardGroup','ConstRoute'=>'sys\fortunateawardgroup\Constant','Type'=>'SYS');
    public static $AwardTimeDrop = array('Name'=>'AwardTimeDrop','Route'=>'sys\awardtimedrop\AwardTimeDrop','ConstRoute'=>'sys\awardtimedrop\Constant','Type'=>'SYS');
    public static $EquipEffect = array('Name'=>'EquipEffect','Route'=>'sys\equipeffect\EquipEffect','ConstRoute'=>'sys\equipeffect\Constant','Type'=>'SYS');
    public static $ActivityGui = array('Name'=>'ActivityGui','Route'=>'sys\activitygui\ActivityGui','ConstRoute'=>'sys\activitygui\Constant','Type'=>'SYS');
    public static $WhiteList = array('Name'=>'WhiteList','Route'=>'sys\whitelist\WhiteList','ConstRoute'=>'sys\whitelist\Constant','Type'=>'SYS');
    public static $Misc = array('Name'=>'Misc','Route'=>'sys\misc\Misc','ConstRoute'=>'sys\misc\Constant','Type'=>'SYS');
    public static $StaticSlotMachine = array('Name'=>'StaticSlotMachine','Route'=>'sys\slotmachine\StaticSlotMachine','ConstRoute'=>'sys\slotmachine\Constant','Type'=>'SYS');
    public static $SlotMachineType = array('Name'=>'SlotMachineType','Route'=>'sys\slotmachinetype\SlotMachineType','ConstRoute'=>'sys\slotmachinetype\Constant','Type'=>'SYS');
    public static $SlotMachineGroup = array('Name'=>'SlotMachineGroup','Route'=>'sys\slotmachinegroup\SlotMachineGroup','ConstRoute'=>'sys\slotmachinegroup\Constant','Type'=>'SYS');
    public static $SkyLevelAward = array('Name'=>'SkyLevelAward','Route'=>'sys\skylevelaward\SkyLevelAward','ConstRoute'=>'sys\skylevelaward\Constant','Type'=>'SYS');
    public static $SlotMachineRankAward = array('Name'=>'SlotMachineRankAward','Route'=>'sys\slotmachinerankaward\SlotMachineRankAward','ConstRoute'=>'sys\slotmachinerankaward\Constant','Type'=>'SYS');
    public static $StaticActivityBox = array('Name'=>'StaticActivityBox','Route'=>'sys\activitybox\StaticActivityBox','ConstRoute'=>'sys\activitybox\Constant','Type'=>'SYS');
    public static $BoxStep = array('Name'=>'BoxStep','Route'=>'sys\boxstep\BoxStep','ConstRoute'=>'sys\boxstep\Constant','Type'=>'SYS');
    public static $Box = array('Name'=>'Box','Route'=>'sys\box\Box','ConstRoute'=>'sys\box\Constant','Type'=>'SYS');
    public static $BoxRankAward = array('Name'=>'BoxRankAward','Route'=>'sys\boxrankaward\BoxRankAward','ConstRoute'=>'sys\boxrankaward\Constant','Type'=>'SYS');
    public static $StrongholdAward = array('Name'=>'StrongholdAward','Route'=>'sys\strongholdaward\StrongholdAward','ConstRoute'=>'sys\strongholdaward\Constant','Type'=>'SYS');
    public static $StrongholdDkpScore = array('Name'=>'StrongholdDkpScore','Route'=>'sys\strongholddkpscore\StrongholdDkpScore','ConstRoute'=>'sys\strongholddkpscore\Constant','Type'=>'SYS');
    public static $WeekTitle = array('Name'=>'WeekTitle','Route'=>'sys\weektitle\WeekTitle','ConstRoute'=>'sys\weektitle\Constant','Type'=>'SYS');
    public static $CrossModule = array('Name'=>'CrossModule','Route'=>'sys\crossmodule\CrossModule','ConstRoute'=>'sys\crossmodule\Constant','Type'=>'SYS');
    public static $FormationLinkage = array('Name'=>'FormationLinkage','Route'=>'sys\formationlinkage\FormationLinkage','ConstRoute'=>'sys\formationlinkage\Constant','Type'=>'SYS');
    public static $PlatformCharge = array('Name'=>'PlatformCharge','Route'=>'sys\platformcharge\PlatformCharge','ConstRoute'=>'sys\platformcharge\Constant','Type'=>'SYS');
    public static $ShipStar = array('Name'=>'ShipStar','Route'=>'sys\shipstar\ShipStar','ConstRoute'=>'sys\shipstar\Constant','Type'=>'SYS');
    public static $ShipLevel = array('Name'=>'ShipLevel','Route'=>'sys\shiplevel\ShipLevel','ConstRoute'=>'sys\shiplevel\Constant','Type'=>'SYS');
    public static $BuildingItem = array('Name'=>'BuildingItem','Route'=>'sys\builditem\BuildingItem','ConstRoute'=>'sys\builditem\Constant','Type'=>'SYS');
    public static $Gear = array('Name'=>'Gear','Route'=>'sys\gear\Gear','ConstRoute'=>'sys\gear\Constant','Type'=>'SYS');
    public static $GearLevel = array('Name'=>'GearLevel','Route'=>'sys\gearlevel\GearLevel','ConstRoute'=>'sys\gearlevel\Constant','Type'=>'SYS');
    public static $GearGrade = array('Name'=>'GearGrade','Route'=>'sys\geargrade\GearGrade','ConstRoute'=>'sys\geargrade\Constant','Type'=>'SYS');
    public static $ExploreAward = array('Name'=>'ExploreAward','Route'=>'sys\exploreaward\ExploreAward','ConstRoute'=>'sys\exploreaward\Constant','Type'=>'SYS');
    public static $SolarArea = array('Name'=>'SolarArea','Route'=>'sys\solararea\SolarArea','ConstRoute'=>'sys\solararea\Constant','Type'=>'SYS');
    public static $LootingAward = array('Name'=>'LootingAward','Route'=>'sys\lootingaward\LootingAward','ConstRoute'=>'sys\lootingaward\Constant','Type'=>'SYS');
    public static $VirtualFleetSet = array('Name'=>'VirtualFleetSet','Route'=>'sys\virtualfleetset\VirtualFleetSet','ConstRoute'=>'sys\virtualfleetset\Constant','Type'=>'SYS');
    public static $RandName = array('Name'=>'RandName','Route'=>'sys\randname\RandName','ConstRoute'=>'sys\randname\Constant','Type'=>'SYS');
    public static $ExpeditionZone = array('Name'=>'ExpeditionZone','Route'=>'sys\expeditionzone\ExpeditionZone','ConstRoute'=>'sys\expeditionzone\Constant','Type'=>'SYS');
    public static $RuinsClass = array('Name'=>'RuinsClass','Route'=>'sys\ruinsclass\RuinsClass','ConstRoute'=>'sys\ruinsclass\Constant','Type'=>'SYS');
    public static $RuinsCost = array('Name'=>'RuinsCost','Route'=>'sys\ruinscost\RuinsCost','ConstRoute'=>'sys\ruinscost\Constant','Type'=>'SYS');
    public static $FuncOpen = array('Name'=>'FuncOpen','Route'=>'sys\funcopen\FuncOpen','ConstRoute'=>'sys\funcopen\Constant','Type'=>'SYS');
    public static $DefenseNpc = array('Name'=>'DefenseNpc','Route'=>'sys\defensenpc\DefenseNpc','ConstRoute'=>'sys\defensenpc\Constant','Type'=>'SYS');
    public static $TechLevel = array('Name'=>'TechLevel','Route'=>'sys\techlevel\TechLevel','ConstRoute'=>'sys\techlevel\Constant','Type'=>'SYS');
    public static $GoldBox = array('Name'=>'GoldBox','Route'=>'sys\goldbox\GoldBox','ConstRoute'=>'sys\goldbox\Constant','Type'=>'SYS');
    public static $CheckTable = array('Name'=>'CheckTable','Route'=>'sys\checktable\CheckTable','ConstRoute'=>'sys\checktable\Constant','Type'=>'SYS');
    public static $StarShipRemake = array('Name'=>'StarShipRemake','Route'=>'sys\starshipremake\StarShipRemake','ConstRoute'=>'sys\starshipremake\Constant','Type'=>'SYS');
    public static $StarShipRemakeLevel = array('Name'=>'StarShipRemakeLevel','Route'=>'sys\starshipremakelevel\StarShipRemakeLevel','ConstRoute'=>'sys\starshipremakelevel\Constant','Type'=>'SYS');
    public static $StarShipAbility = array('Name'=>'StarShipAbility','Route'=>'sys\starshipability\StarShipAbility','ConstRoute'=>'sys\starshipability\Constant','Type'=>'SYS');
    public static $DetectionTask = array('Name'=>'DetectionTask','Route'=>'sys\detectiontask\DetectionTask','ConstRoute'=>'sys\detectiontask\Constant','Type'=>'SYS');
    public static $Lotery = array('Name'=>'Lotery','Route'=>'sys\lotery\Lotery','ConstRoute'=>'sys\lotery\Constant','Type'=>'SYS');
    public static $LoteryClass = array('Name'=>'LoteryClass','Route'=>'sys\loteryclass\LoteryClass','ConstRoute'=>'sys\loteryclass\Constant','Type'=>'SYS');
    public static $ServerGoal = array('Name'=>'ServerGoal','Route'=>'sys\servergoal\ServerGoal','ConstRoute'=>'sys\servergoal\Constant','Type'=>'SYS');
    public static $RaiderArkActivity = array('Name'=>'RaiderArkActivity','Route'=>'sys\raiderarkactivity\RaiderArkActivity','ConstRoute'=>'sys\raiderarkactivity\Constant','Type'=>'SYS');
    public static $RaiderArkLevel = array('Name'=>'RaiderArkLevel','Route'=>'sys\raiderarklevel\RaiderArkLevel','ConstRoute'=>'sys\raiderarklevel\Constant','Type'=>'SYS');
    public static $StarshipProperty = array('Name'=>'StarshipProperty','Route'=>'sys\starshipproperty\StarshipProperty','ConstRoute'=>'sys\starshipproperty\Constant','Type'=>'SYS');
    public static $HonorMedal = array('Name'=>'HonorMedal','Route'=>'sys\honormedal\HonorMedal','ConstRoute'=>'sys\honormedal\Constant','Type'=>'SYS');
    public static $HonorMedalPro = array('Name'=>'HonorMedalPro','Route'=>'sys\honormedalpro\HonorMedalPro','ConstRoute'=>'sys\honormedalpro\Constant','Type'=>'SYS');
    public static $HonorMedalSuit = array('Name'=>'HonorMedalSuit','Route'=>'sys\honormedalsuit\HonorMedalSuit','ConstRoute'=>'sys\honormedalsuit\Constant','Type'=>'SYS');
    public static $HFrontLineActivity = array('Name'=>'HFrontLineActivity','Route'=>'sys\hfrontlineactivity\HFrontLineActivity','ConstRoute'=>'sys\hfrontlineactivity\Constant','Type'=>'SYS');
    public static $HFrontLineAward = array('Name'=>'HFrontLineAward','Route'=>'sys\hfrontlineaward\HFrontLineAward','ConstRoute'=>'sys\hfrontlineaward\Constant','Type'=>'SYS');
    public static $ExchangeGroup = array('Name'=>'ExchangeGroup','Route'=>'sys\exchangegroup\ExchangeGroup','ConstRoute'=>'sys\exchangegroup\Constant','Type'=>'SYS');
    public static $DataVer = array('Name'=>'DataVer','Route'=>'sys\dataver\DataVer','ConstRoute'=>'sys\dataver\Constant','Type'=>'SYS');
    public static $SchedulerTimer = array('Name'=>'SchedulerTimer','Route'=>'sys\schedulertimer\SchedulerTimer','ConstRoute'=>'sys\schedulertimer\Constant','Type'=>'SYS');
    public static $DeathBattleActivity = array('Name'=>'DeathBattleActivity','Route'=>'sys\deathbattleactivity\DeathBattleActivity','ConstRoute'=>'sys\deathbattleactivity\Constant','Type'=>'SYS');
    public static $DeathBattleMultiKill = array('Name'=>'DeathBattleMultiKill','Route'=>'sys\deathbattlemultikill\DeathBattleMultiKill','ConstRoute'=>'sys\deathbattlemultikill\Constant','Type'=>'SYS');
    public static $DeathBattleActiveChest = array('Name'=>'DeathBattleActiveChest','Route'=>'sys\deathbattleactivechest\DeathBattleActiveChest','ConstRoute'=>'sys\deathbattleactivechest\Constant','Type'=>'SYS');
    public static $DeathBattleEndAward = array('Name'=>'DeathBattleEndAward','Route'=>'sys\deathbattleendaward\DeathBattleEndAward','ConstRoute'=>'sys\deathbattleendaward\Constant','Type'=>'SYS');
    public static $LanDb = array('Name'=>'LanDb','Route'=>'sys\landb\LanDb','ConstRoute'=>'sys\landb\Constant','Type'=>'SYS');
    public static $FighterCareer = array('Name'=>'FighterCareer','Route'=>'sys\fightercareer\FighterCareer','ConstRoute'=>'sys\fightercareer\Constant','Type'=>'SYS');
    public static $FighterSuit = array('Name'=>'FighterSuit','Route'=>'sys\fightersuit\FighterSuit','ConstRoute'=>'sys\fightersuit\Constant','Type'=>'SYS');
    public static $FighterGrade = array('Name'=>'FighterGrade','Route'=>'sys\fightergrade\FighterGrade','ConstRoute'=>'sys\fightergrade\Constant','Type'=>'SYS');
    public static $FighterLevel = array('Name'=>'FighterLevel','Route'=>'sys\fighterlevel\FighterLevel','ConstRoute'=>'sys\fighterlevel\Constant','Type'=>'SYS');
    public static $CustomFunction = array('Name'=>'CustomFunction','Route'=>'sys\customfunction\CustomFunction','ConstRoute'=>'sys\customfunction\Constant','Type'=>'SYS');
    public static function getMesByName($name)
    {
        $result = null;
        @eval('$result = self::$'.$name.';');
        if (empty($result)) throw new GameException(Error::OBJ_NONE_INITIALIZED);
        return $result;
    }
}